name: AntSim
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: jadedResearcher <gtg287y@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  dynamicMusic:
    git: git://github.com/FarragoFiction/dynamicMusic.git

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.6.0
  dwds: ^7.1.1

